function optical_design_ABCD(filename)

%This function reads in input the .mat file
%generated by "optical_design_GUI.m" and
%computes design relevant quantities with
%the paraxial ABCD matrix formalism

if exist(filename)==2
   load(filename);
else
   disp(strcat([filename,' does not exist as an .mat file']))
   return
end

ABCD=[1 0;0 1];
for h=1:length(A.optics)
   L=A.optics(h).d;
   F=A.optics(h).F;
   ABCD=[1 0;-1/F 1]*[1 L;0 1]*ABCD;
end
Limg=-ABCD(1,2)/ABCD(2,2);
M=ABCD(1,1)+Limg*ABCD(2,1);
disp(strcat(['Net magnification: ',num2str(M)]))
disp(strcat(['Distance from last lens to image plane: ',num2str(Limg)]))

[1 0.599;0 1]*ABCD
